blog_site/blog_site/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('catalog/', include('catalog.urls')),
    path('', RedirectView.as_view(url='/catalog/', permanent=True)),
    path('accounts/', include('django.contrib.auth.urls')),
]

static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

blog_site/catalog/urls.py
from django.urls import re_path, path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    re_path(r'^posts/$', views.PostListView.as_view(), name='posts'),
    re_path(r'^post/(?P<pk>\d+)$', views.PostDetailView.as_view(), name='post-detail'),
    re_path(r'^authors/$', views.AuthorListView.as_view(), name='authors'),
    re_path(r'^author/(?P<pk>\d+)$', views.AuthorDetailView.as_view(), name='author-detail'),
    re_path(r'^post/(?P<pk>\d+)/comment_create/$', views.CommentCreate.as_view(), name='comment_create'),
]

blog_site/catalog/models.py
from datetime import datetime
from django.db import models
from django.urls import reverse
from django.forms import ModelForm

# Create your models here.

class Post(models.Model):
    title = models.CharField(max_length=100)
    author = models.ForeignKey('Author', on_delete=models.SET_NULL, null=True)
    publish_date = models.DateField('pubdate', default=datetime.today(), auto_now_add=False)
    description = models.TextField(max_length=2000, blank=False, help_text="Write your massege")

    def __str__(self):
        """
        String for representing the Model object.
        """
        return self.title

    class Meta:
        ordering =['-publish_date']

    def get_absolute_url(self):
        """
        Returns the url to access a particular instance of the model.
        """
        return reverse('post-detail', args=[str(self.id)])

class Author(models.Model):
    name = models.CharField(max_length=20)
    info = models.TextField('authors_info', max_length=200, null=True, help_text="About you...")

    def __str__(self):
        """
        String for representing the Model object.
        """
        return self.name

    def get_absolute_url(self):
        """
        Returns the url to access a particular instance of the model.
        """
        return reverse('author-detail', args=[str(self.id)])

class Comment(models.Model):
    comment_text = models.TextField(max_length=1000, help_text="Write your comment, don`t use insults and curses")
    post = models.ForeignKey('Post', on_delete=models.SET_NULL, null=True)
    publish_date = models.DateField('pubdate', default=datetime.today(), auto_now_add=False)

    def __str__(self):
        """
        String for representing the Model object.
        """
        return self.comment_text[:75]

    class Meta:
        ordering =['publish_date']

blog_site/catalog/forms.py
from django import forms

from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _

class CreateComment(forms.Form):
    comment_text = forms.CharField(help_text="Write your comment, don`t use insults and curses")

blog_site/catalog/views.py
from django.shortcuts import render


from .models import Author, Post, Comment


def index(request):
    # Генерация главных объектов
    num_posts=Post.objects.all().count()
    num_comments=Comment.objects.count()
    num_authors=Author.objects.count()

    # Отрисовка HTML-шаблона index.html с данными внутри
    # переменной контекста context
    return render(
        request,
        'index.html',
        context={'num_posts':num_posts, 'num_comments':num_comments, 'num_authors':num_authors},
    )

from django.views import generic

class PostListView(generic.ListView):
    model = Post
    paginate_by = 5

class PostDetailView(generic.DetailView):
    model = Post

class AuthorListView(generic.ListView):
    model = Author

class AuthorDetailView(generic.DetailView):
    model = Author

from django.views.generic.edit import CreateView
from django.urls import reverse
from django.shortcuts import get_object_or_404


class CommentCreate(CreateView):

    model = Comment
    fields = ['comment_text', ]

    def get_context_data(self, **kwargs):

        context = super(CommentCreate, self).get_context_data(**kwargs)
        context['post'] = get_object_or_404(Post, pk=self.kwargs['pk'])
        return context

    def form_valid(self, form):

        form.instance.author = self.request.user
        form.instance.post = get_object_or_404(Post, pk=self.kwargs['pk'])
        return super(CommentCreate, self).form_valid(form)

    def get_success_url(self):

        return reverse('post-detail', kwargs={'pk': self.kwargs['pk'], })

blog_site/catalog/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>

  {% block title %}<title>Blogger</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

  <!-- Добавление дополнительного статического CSS файла -->
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>

<body>

  <div class="container-fluid">

    <div class="row">
      <div class="col-sm-2">
      {% block sidebar %}
      <ul class="sidebar-nav">
          <li><a href="{% url 'index' %}">Home</a></li>
          <li><a href="{% url 'posts' %}">All posts</a></li>
          <li><a href="{% url 'authors' %}">All authors</a></li>

          {% if user.is_authenticated %}
              <li>User: {{ user.get_username }}</li>
              <li><a href="">My posts</a></li>
              <li><a href="{% url 'logout'%}?next={{request.path}}">Logout</a></li>

           {% else %}
             <li><a href="{% url 'login'%}?next={{request.path}}">Login</a></li>
           {% endif %}
      </ul>
     {% endblock %}


      </div>
      <div class="col-sm-10 ">
      {% block content %}{% endblock %}

          {% block pagination %}
              {% if is_paginated %}
                  <div class="pagination">
                      <span class="page-links">
                          {% if page_obj.has_previous %}
                              <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
                          {% endif %}
                          <span class="page-current">
                              Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                          </span>
                          {% if page_obj.has_next %}
                              <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
                          {% endif %}
                      </span>
                  </div>
              {% endif %}
            {% endblock %}
      </div>
    </div>

  </div>
</body>
</html>

blog_site/catalog/templates/catalog/author_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>{{ author.name }}</h1>

  {% if info %}
  <p><strong>About author</strong> </p> <!-- author detail link not yet defined -->
  <p>{{author.info}}</p>
  {%endif%}

  <p><strong>Posts:</strong></p>

  <div style="margin-left:30px;margin-top:30px">
  {% for post in author.post_set.all %}
      <p><a href="{{post.get_absolute_url}}">{{post.title}}</a>  {{post.publish_date}}</p>
<!-- итерации по каждой копии/экземпляру книги -->
  {% endfor %}
  </div>

{% endblock %}

blog_site/catalog/templates/catalog/author_list.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Author List</h1>

    {% if author_list %}
    <ul>

      {% for author in author_list %}
      <li>
        <a href=" {{author.get_absolute_url}}">{{ author }}</a>
      </li>
      {% endfor %}

    </ul>
    {% else %}
      <p>There are no authors in the site.</p>
    {% endif %}
{% endblock %}

blog_site/catalog/templates/catalog/comment_form.html
{% extends "base_generic.html" %}

{% block content %}
<h1>{{ post.title }}</h1>

  <p><strong>Author:</strong> {{ post.author }}</p>
  <p><strong>Publish date:</strong> {{ post.publish_date }}</p>
  <h4>{{ post.description }}</h4>

{% if user.is_authenticated %}
    <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Add comment" />
    </form>
{%endif%}

{% endblock %}

blog_site/catalog/templates/catalog/post_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>{{ post.title }}</h1>

  <p><strong>Author:</strong> {{ post.author }}</p>
  <p><strong>Publish date:</strong> {{ post.publish_date }}</p>
  <h4>{{ post.description }}</h4>

  <div style="margin-left:10px;margin-top:20px">
      <p><strong>Comments:</strong></p>
    </div>
  <div style="margin-left:30px;margin-top:30px">
  {% for comment in post.comment_set.all %}
      <p>{{comment.comment_text}}</p>
  {% endfor %}
  </div>

{% if user.is_authenticated %}

<li><a href="{% url 'comment_create' post.id %}"> Add comment</a> </li>
{% else %}
<li><p>If you want add comment you must <a href="{% url 'login'%}?next={{request.path}}">Login</a></p></li>
{%endif%}


{% endblock %}

blog_site/catalog/templates/catalog/post_list.html
{% extends "base_generic.html" %}

{% block content %}
<h1>Posts list</h1>

    {% if post_list %}
    <ul>

      {% for post in post_list %}
      <li>
          <a href="{{ post.get_absolute_url }}">{{ post.title }}</a> <em>{{post.publish_date}}</em>
        <a href="{{ post.author.get_absolute_url }}">{{ post.author }}</a>
      </li>
      {% endfor %}

    </ul>
    {% else %}
      <p>There are no posts in the library.</p>
    {% endif %}
{% endblock %}

blog_site/catalog/templates/index.html
{% extends "base_generic.html" %}

{% block content %}
<h1>Blogger</h1>
<p>Welcome to <em>Blogger</em>, a little site were you may adding your experions and thikns about differet topiks.</p>


<h3>At this moment we have</h3>

  <ul>
    <li><strong>Posts:</strong> {{ num_posts }}</li>
    <li><strong>Authors:</strong> {{ num_authors }}</li>
    <li><strong>Comments:</strong> {{ num_comments }}</li>

  </ul>
<p>Made by <em>Danil Shvecov</em></p>
  {% load static %}

{% endblock %}